name: ci

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run ./ci/steps/fmt.sh
        run: |
          GO111MODULE=on
          go get -u github.com/mvdan/sh/cmd/shfmt/
          go get -u github.com/goreleaser/nfpm
          ./ci/steps/fmt.sh

      - name: Run ./ci/steps/lint.sh
        run: ./ci/steps/lint.sh

      - name: Run ./ci/steps/test.sh
        run: ./ci/steps/test.sh

      - name: Run ./ci/steps/test.sh
        run: ./ci/steps/test.sh

      - name: Run ./ci/steps/release.sh
        run: ./ci/steps/release.sh

      - name: Upload npm package artifact
        uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: ./release-npm-package

  linux-amd64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download npm package
        uses: actions/download-artifact@v2
        with:
          name: npm-package
          path: ./release-npm-package
      
      - name: Run ./ci/steps/release-packages.sh
        run: ./ci/steps/release-packages.sh
      
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-packages
          path: ./release-packages
